#!/bin/sh

git sparse-checkout add set;
echo "# ASPNETCore.gitignore";
git sparse-checkout add ./templates/ASPNETCore.gitignore;

echo "# Archive.gitignore";
git sparse-checkout add ./templates/Archive.gitignore;

echo "# Git.gitignore";
git sparse-checkout add ./templates/Git.gitignore;

echo "# VisualStudio.gitignore";
git sparse-checkout add ./templates/VisualStudio.gitignore;

echo "# VisualStudio.patch";
git sparse-checkout add ./templates/VisualStudio.patch;

echo "# VisualStudioCode.gitignore";
git sparse-checkout add ./templates/VisualStudioCode.gitignore;

echo "# Text.gitignore";
git sparse-checkout add ./templates/Text.patch;

echo "# certificates.gitignore";
git sparse-checkout add ./templates/Text.patch;

echo "# macOS.gitignore";
git sparse-checkout add ./templates/macOS.gitignore;

echo "# Windows.gitignore";
git sparse-checkout add ./templates/Windows.gitignore;

echo "# backroom.gitignore";
git sparse-checkout add ./backroom.gitignore;